CREATE DATABASE LOGIN;

CREATE TABLE SESION( 
IDUsuario CHAR(20), 
CONTRA VARCHAR(20)
);
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Nilton', 'nilton123'); 
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Jose', 'jose1234');
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Andre', 'andre123');
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Carlo', 'carlo123');
SELECT * FROM SESION;