CREATE DATABASE LOGIN;

CREATE TABLE SESION( 
IDUsuario CHAR(8), 
CONTRA VARCHAR(15)
);
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Nilton', 'nilton123'); 
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Jose', 'jose1234');
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Andre', 'andre123');
SELECT * FROM SESION;